# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Qualcomm SoCs built-in PPE device driver
#

obj-$(CONFIG_QCOM_PPE) += qcom-ppe.o
qcom-ppe-objs := ppe.o ppe_ops.o ppe_debugfs.o ppe_uniphy.o
